Trying the workflow

diff --git a/.github/workflows/deploy_infra.yml b/.github/workflows/deploy_infra.yml
--- a/.github/workflows/deploy_infra.yml
+++ b/.github/workflows/deploy_infra.yml
@@ -6,7 +6,6 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -34,7 +33,12 @@ jobs:
       - name: Terraform Apply
         run: terraform apply -auto-approve
         working-directory: ./terraform
-
+        #Debug step
+      - name: Debug Terraform Version and Path
+        run: |
+          which terraform
+          terraform version
+        working-directory: ./terraform
 
       - name: Output ALB DNS Name (clean)
         run: |
@@ -48,11 +52,24 @@ jobs:
           name: alb-dns
           path: ./terraform/alb_dns_name.txt
 
+        #Debug step
+      - name: Debug ALB DNS Name content
+        run: cat ./terraform/alb_dns_name.txt
+
+        #Debug step
+      - name: Verify ALB DNS Name
+        run: |
+          echo "ALB DNS Name:"
+          cat ./alb_dns_name.txt
+          if [ ! -s ./alb_dns_name.txt ]; then
+            echo "ERROR: alb_dns_name.txt is empty"
+            exit 1
+          fi
+        working-directory: ./terraform
 
   simulate:
     needs: deploy
     runs-on: ubuntu-latest
-
     steps:
       - name: Wait for infra to settle
         run: sleep 60
