Changed the flow

diff --git a/.github/workflows/deploy_infra.yml b/.github/workflows/deploy_infra.yml
--- a/.github/workflows/deploy_infra.yml
+++ b/.github/workflows/deploy_infra.yml
@@ -32,10 +32,20 @@ jobs:
       - name: Terraform Apply
         run: terraform apply -auto-approve
         working-directory: ./terraform
+#Debug step
+      - name: Debug Terraform Version and Path
+        run: |
+          which terraform
+          terraform version
+        working-directory: ./terraform
+
 
       - name: Output ALB DNS Name
-        run: terraform output -raw alb_dns_name > alb_dns_name.txt
+        run: |
+          set -o pipefail            # fail if any command fails
+          terraform output -raw alb_dns_name > alb_dns_name.txt
         working-directory: ./terraform
+
 
       - name: Upload ALB DNS Name Artifact
         uses: actions/upload-artifact@v4
@@ -43,8 +53,21 @@ jobs:
           name: alb-dns
           path: terraform/alb_dns_name.txt
 
+#Debug step
       - name: Debug ALB DNS Name content
         run: cat ./terraform/alb_dns_name.txt
+
+#Debug step
+      - name: Verify ALB DNS Name
+        run: |
+          echo "ALB DNS Name:"
+          cat ./alb_dns_name.txt
+          if [ ! -s ./alb_dns_name.txt ]; then
+            echo "ERROR: alb_dns_name.txt is empty"
+            exit 1
+          fi
+        working-directory: ./terraform
+
 
 
   simulate:
